openapi: 3.2.0
info:
  title: Zoom REST Group API
  description: API Description
  contact:
    name: Zoom Developers
    url: https://zoom.us/developer
    email: developer@zoom.us
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
servers:
- url: https://api.zoom.us/v1
security:
- api_key: []
- api_secret: []
tags:
- name: Group
  description: Group operations
paths:
  /group/create:
    post:
      tags:
      - Group
      description: Create a group on Zoom, return the new group info.
      operationId: groupCreate
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - name
              type: object
              properties:
                name:
                  type: string
                  description: Group name, must be unique in one account.
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                group_id: unique_id
                account_id: unique_id
                name: New Group Test
                total_members: 0
      summary: Group create
      x-summary-source: derived
  /group/delete:
    post:
      tags:
      - Group
      description: Delete a group on Zoom, return the deleted group ID.
      operationId: groupDelete
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: unique_id
                deleted_at: 2015-08-20 08:41:58+00:00
                deleted_count: 1
      summary: Group delete
      x-summary-source: derived
  /group/edit:
    post:
      tags:
      - Group
      description: Edit a group on Zoom, return the new group info.
      operationId: groupEdit
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
                name:
                  type: string
                  description: Group name, must be unique in one account.
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                group_id: unique_id
                account_id: unique_id
                name: New Group Test
                total_members: 0
      summary: Group edit
      x-summary-source: derived
  /group/get:
    post:
      tags:
      - Group
      description: Get a group on Zoom via ID, return the group info.
      operationId: groupGet
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                group_id: unique_id
                account_id: unique_id
                name: Group Test
                total_members: 2
      summary: Group get
      x-summary-source: derived
  /group/list:
    post:
      tags:
      - Group
      description: List all groups on your Zoom account.
      operationId: groupList
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - api_key
              - api_secret
              type: object
              properties:
                api_key:
                  type: string
                  description: Your API Key
                api_secret:
                  type: string
                  description: Your API Secret
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                total_records: 1
                groups:
                - group_id: unique_id
                  account_id: unique_id
                  name: Group Test1
                  total_members: 40
      summary: Group list
      x-summary-source: derived
  /group/member/add:
    post:
      tags:
      - Group
      description: Add members to a group on Zoom.
      operationId: groupMemberAdd
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              - member_ids
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
                member_ids:
                  type: string
                  description: The member IDs, separated by comma
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: unique_id
                add_at: 2015-08-20 08:57:38+00:00
                add_count: 2
      summary: Group member add
      x-summary-source: derived
  /group/member/delete:
    post:
      tags:
      - Group
      description: Delete members of a group on Zoom.
      operationId: groupMemberDelete
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              - member_ids
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
                member_ids:
                  type: string
                  description: The member IDs, separated by comma
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                id: unique_id
                deleted_at: 2015-08-20 08:57:38+00:00
                deleted_count: 2
      summary: Group member delete
      x-summary-source: derived
  /group/member/list:
    post:
      tags:
      - Group
      description: Lists the members of a group on Zoom.
      operationId: groupMemberList
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              required:
              - id
              type: object
              properties:
                id:
                  type: string
                  description: Group ID.
                page_size:
                  type: string
                  description: The amount of records returns within a single API call. Defaults to 30.
                  default: '30'
                page_number:
                  type: string
                  description: Current page number of returned records. Default to 1.
                  default: '1'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              example:
                page_count: 1
                page_number: 1
                page_size: 30
                total_records: 1
                members:
                - id: unique_id
                  email: email_address
                  first_name: Zoomie
                  last_name: Userton
                  pic_url: https://ssotest.zoom.us/p/6EoubcvJR7eF2grNXJkrHA/f2003a9c-3095-4865-8536-03cc6f211e86-9569
      summary: Group member list
      x-summary-source: derived
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: query
    api_secret:
      type: apiKey
      name: api_secret
      in: query
externalDocs:
  description: Zoom REST API Documentation
  url: https://zoom.github.io/api
